apiVersion: v1
kind: Service
metadata:
  name: {{ include "u2p050-twitterfetcher.fullname" . }}
  labels: {{- include "u2p050-twitterfetcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9191
      protocol: TCP
      name: http
  selector:
    {{- include "u2p050-twitterfetcher.selectorLabels" . | nindent 4 }}
